[dbx_rs_test]
homePath = $SPLUNK_DB/dbx_rs_test/db
coldPath = $SPLUNK_DB/dbx_rs_test/colddb
thawedPath = $SPLUNK_DB/dbx_rs_test/thaweddb
maxDataSize = 100
maxTotalDataSizeMB = 256
frozenTimePeriodInSecs = 604800
