[monitor://$SPLUNK_HOME/var/log/splunk/dbx-trace.log*]
disabled = false
index = _internal
sourcetype = dbx_rs:trace:json

[script://$SPLUNK_HOME/etc/apps/TA-dbx-rs/bin/dbx-rs-daemon run]
disabled = false
interval = 0
start_by_shell = false
index = _internal
sourcetype = dbx_rs:daemon:stdout
