[dbx_rs:trace:json]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
INDEXED_EXTRACTIONS = JSON
KV_MODE = none
TIMESTAMP_FIELDS = timestamp_epoch

[dbx_rs:database:row]
SHOULD_LINEMERGE = false
TRUNCATE = 0
INDEXED_EXTRACTIONS = JSON
KV_MODE = none
